### PR TITLE
Bump savon and httpi to lastest version

### PR DESCRIPTION
**Pull request by j133y**
This PR introduces the following changes:

* [Update savon version from v2.3.0 to v2.11.0 changes](https://github.com/savonrb/savon/compare/v2.3.0...v2.11.0)
* [Update httpi version from v0.9.6 to v2.3.0 changes](https://github.com/savonrb/httpi/compare/v0.9.6...v2.4.0)

### CODE REVIEW

**Comment by no-donuts-for-you** [comment]
:facepunch:

**Comment by wevtimoteo** [comment]
It's nice to give more details about changes :)

* [savon from v2.3.0 to v2.11.0 changes](https://github.com/savonrb/savon/compare/v2.3.0...v2.11.0)
* [httpi from v0.9.6 to v2.4.0 changes](https://github.com/savonrb/httpi/compare/v0.9.6...v2.4.0)

As `savon v2.11.0` [relies](https://github.com/savonrb/savon/blob/v2.11.0/savon.gemspec#L21) in `v2.3.0` for `httpi`,  I think its better to keep the same version for `httpi` also :)

**Comment by j133y** [comment]
@wevtimoteo Thanks for noticing that, here is the fix https://github.com/Baby-com-br/braspag/commit/566d73eb25e6066be9c3394b9617e3ec270b26a5

**Comment by wevtimoteo** [comment]
Consider my comment, then :rocket:

**Comment by antoniofilho** [comment]
:+1:

**Pull request merged**
